### ISSUE TITLE
Getting an error when try to set background image for second time

### ISSUE THREAD

**Issue by shkhalid** [artf/grapesjs-style-bg#17]
This plugin allow me to set background only once. 
After saving the data when i click on the same element i am getting this.

This error is appearing when an element have some background image 
<img width="1414" alt="Screen Shot 2021-10-22 at 5 28 08 PM" src="https://user-images.githubusercontent.com/8138036/138454121-52cc3547-e6a9-4c76-8d1a-127232b48d67.png">

**Comment by artf** [comment]
I'm closing this due to a release of a new [version](https://github.com/artf/grapesjs-style-bg/releases/tag/v2.0.1) and I'd expect this to be fixed.
