### ISSUE TITLE
I can't put hex color code using grapesjs-style-bg 

### ISSUE THREAD

**Issue by YaseenHajajweh** [artf/grapesjs-style-bg#19]
There is something weird in the plugin, previously I was able to put a hex color code inside the color section, now I can't.
I think the problem is that :
The type is not defined in => typeProps: ƒ typeProps(result, type) ...

@artf 
<img width="241" alt="Screen Shot 2022-02-03 at 11 13 37 AM" src="https://user-images.githubusercontent.com/31201814/152343893-be973574-ad22-4b9e-9ec8-ad298e566adf.png">

**Comment by artf** [comment]
If you're using the latest grapesjs release (> v0.18.*), this plugin won't work, check the release note here https://github.com/artf/grapesjs/releases/tag/v0.18.1
