### ISSUE TITLE
Problem with new version of grapesjs

### ISSUE THREAD

**Issue by javadsamiee** [artf/grapesjs-style-bg#24]
I have updated grapesjs to the version 18.0.4 and now after click on gradient and color just see images and I can not change between them, what is the stable version of grapesjs for this plugin and did you check this plugin with newest verion of grapesjs?

**Comment by DavidHarvey** [comment]
Relevant comment from author (plugin is intentionally not supported on latest Grapes until updated): https://github.com/artf/grapesjs/issues/4257#issuecomment-1099215072

**Comment by bit-ocean** [comment]
The gradient and color selection doesn't seem to work on versions later than 0.17.29. Checked with 0.19. and 0.20. It's the feature that keeps me from upgrading to later versions of grapesjs. Is there a plan to fix this this functionality? I find it super important.

Thank you for developing grapesjs!

**Comment by artf** [comment]
New refactored version of the plugin published https://github.com/artf/grapesjs-style-bg/releases/tag/v2.0.1
