### ISSUE TITLE
Settings are not editable on reload

### ISSUE THREAD

**Issue by adamwpe** [artf/grapesjs-style-bg#4]
It appears one save and reload of the page, the editor doesn't allow you to edit the values, but instead when you select 'background' again, it clears them:

E.g. Setting the background
![Capture](https://user-images.githubusercontent.com/49768920/82093935-021f1700-96f4-11ea-95b2-3b7273d2f687.png)
t background

On Save and Reload - you can't edit the settings:
![Capture2](https://user-images.githubusercontent.com/49768920/82093963-1236f680-96f4-11ea-9e9a-f5a04681094b.PNG)

Any workaround on this?

**Comment by egorgripasov** [comment]
+1 - any updates?

**Comment by MarksEliel** [comment]
+1 - any updates?

**Comment by ronaldohoch** [comment]
I tested now, and i can't reproduce, may it have has been corrected

**Comment by rajaomariajaona** [comment]
I have the same issue. When components is set by `editor.setComponent` and the components is string html.

**Comment by artf** [comment]
I'd expect it to be fixed with the new release of the plugin
