### ISSUE TITLE
Issue with build

### ISSUE THREAD

**Issue by vijayshukla30** [artf/grapesjs-style-bg#6]
Hi,
I am getting below issue.
<img width="1432" alt="Screenshot 2020-09-08 at 12 36 42 PM" src="https://user-images.githubusercontent.com/11537372/92444171-1ff71700-f1d0-11ea-8b77-fe7e29ae76de.png">

**Comment by justin3737** [comment]
+1 same as here

**Comment by josh-fnbtech** [comment]
+1 same , any ETA on a fix?

**Comment by YannRostingt** [comment]
+1 same

**Comment by artf** [comment]
I'd expect this to be fixed in the new [version](https://github.com/artf/grapesjs-style-bg/releases/tag/v2.0.1)
