### ISSUE TITLE
Problem with asset manager

### ISSUE THREAD

**Issue by hitaloramon** [artf/grapesjs-style-bg#7]
Hi @artf,

I have a custom asset manager in my project that works normally when I add an image and use it to select an item. However in the style-bg plugin when I click the button to open select an image for the background my file manager opens and when I select the image nothing happens. Is there anything that needs to be done to work in the style-bg plugin?

Obs: I'm using the latest versions of grapejs and the style-bg plugin

`editor.Commands.add('open-assets', {
 run(editor, sender, opts = {}) {...
var image = 'path-img.jpg';
                  opts.target.set('src', image );
 }
 })`

**Comment by sizhousama** [comment]
hi @hitaloramon , 
I have the same problem, is your problem solved ？

**Comment by hitaloramon** [comment]
Hi @sizhousama, 

I managed to resolve it.
I put the complete example, but what suits you is from line 9 to 25 

[`https://pastebin.com/f12dMm9p`](https://pastebin.com/f12dMm9p)

**Comment by mstevens625** [comment]
@hitaloramon,
I have the same issue but your link doesn't appear to work.  Would you mind sharing your solution?

**Comment by hitaloramon** [comment]
@mstevens625 link working

**Comment by mstevens625** [comment]
Thanks @hitaloramon, that helped tremendously.

**Comment by chaegumi** [comment]
I use it with ckfinder,this is my code,it do not work.
```javascript

    cmdm.add('open-assets', {
        run(editor, sender, opts) {
            // console.log(editor)
            // console.log(editor)
            console.log(editor);
            console.log(sender);
            console.log(opts)

            var finder = new CKFinder();
            finder.basePath = '/resource/ckfinder/';
            finder.selectActionFunction = function(fileUrl, data) {
                console.log(opts)
                opts.target.set('src', fileUrl);

                console.log(opts.target)
            }
            finder.selectActionData = '';

            finder.popup();
        }
    });

```

![image](https://user-images.githubusercontent.com/9654650/208573135-97aea0e7-14b6-490f-858a-5ae0e1bb0dee.png)

**Comment by chaegumi** [comment]
This work
```javascript

        assetManager: {
            custom: {
                open(props) {
                    var finder = new CKFinder();

                    finder.basePath = '/resource/ckfinder/';
                    finder.selectActionFunction = function(fileUrl, data) {
                        // opts.target.set('src', fileUrl);
                        props.select(fileUrl);

                        props.close();
                    }
                    finder.selectActionData = '';

                    var api = finder.popup();
                },
                close(props) {
                    // finder.close();
                }
            }
        },

```
