### ISSUE TITLE
There is no display plugin...

### ISSUE THREAD

**Issue by justin3737** [artf/grapesjs-style-bg#9]
hi @artf 
thank you for doing everythings here
but I try to use this plugin but I can't
![img](https://i.imgur.com/gaC65t1.png)
demo
https://jsfiddle.net/e4pbsgm0/

**Comment by mmotov** [comment]
@justin3737 did you managed to solve this? I have the same issue

**Comment by ronaldohoch** [comment]
Same here!

**Comment by ronaldohoch** [comment]
I don't know why, but in the index.html from repo's root folder, it has this code:

```
      editor.StyleManager.addProperty('extra', [{
        name: 'Background',
        property: 'background',
        type: 'bg',
      }]);
```

Also, in the https://grapesjs.com/demo.html we have these config, inside 

```
'gjs-preset-webpage': {
   ... some configs
   customStyleManager: [{
      ...A lot of other configs
      {
         name: 'Decorations'
         properties: [{...},{...},
            {
               id: 'background-bg',
               property: 'background',
               type: 'bg',
            }
        ]
    }]
}
```
![image](https://user-images.githubusercontent.com/2287371/124831947-4e5d9400-df52-11eb-83b1-752db906133e.png)
So... I think we have to configure like it.

But, doing this... We get 2 background configurations in style panel, i'm looking to remove the other background from styles.
If i got some updates, i'll put it here.

**Comment by ronaldohoch** [comment]
So, @artf can say if i'm wrong, but, we can do it:

```
editor.StyleManager.removeProperty("decorations","background-bg")
editor.StyleManager.addProperty('extra', [{
  name: 'Background',
  property: 'background',
  type: 'bg',
}]);
```

**Comment by mmotov** [comment]
@ronaldohoch thanks for sharing, that helped!

**Comment by bernhardmiller** [comment]
I also had this problem, and managed to make it work with a configuration like this:

```
styleManager: {
        // ...
        sectors: [{
            // ...
            buildProps: [
                "background-bg", // ...
            ],
            properties: [
                // ...
                {id: 'background-bg', name: 'Background', property: 'background', type: 'bg' },
            ],
        }],
    },
```

**Comment by artf** [comment]
The new [version](https://github.com/artf/grapesjs-style-bg/releases/tag/v2.0.1) should be easier to use as it extends the built-in background property.
